# Generated by Django 3.2.8 on 2021-10-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211029_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Collection',
        ),
    ]
