# Generated by Django 3.2.8 on 2021-11-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='icon',
            field=models.ImageField(default='sangakara', upload_to='images/'),
            preserve_default=False,
        ),
    ]
