# Generated by Django 3.2.8 on 2021-11-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_collection_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='collection',
        ),
    ]
