# Generated by Django 3.2.8 on 2021-11-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_category_product_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='category',
        ),
    ]
