# Generated by Django 3.2.9 on 2021-11-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
