# Generated by Django 4.0 on 2021-12-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_order_comment_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='shop.customer'),
            preserve_default=False,
        ),
    ]
