# Generated by Django 4.0.1 on 2022-01-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_customer_image_review_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='customer',
        ),
    ]
